
# To start all the services defined in your compose.yaml file
up:
	docker compose -p docker-compose.yml up

# To stop and remove the running services
down:
	docker compose -p docker-compose.yml down

# Monitoring the output of your running containers and debug issues
logs:
	docker compose -p docker-compose.yml logs

# To lists all the services along with their current status
ps:
	docker compose -p docker-compose.yml ps
